### PR TITLE
Fix CLI Excel export creating files with zero bytes

### LINKED ISSUE #104: exporting xlsx via cli creates a file with zero bytes

### PR DESCRIPTION
**Pull request by enesaktay**
fixes #104

### CODE REVIEW

File: src/Writer/WriterInterface.php [hunk 1]
```diff
@@ -20,4 +20,9 @@ public function setFile(string $filename): void;
      * @return string
      */
     public function getFileContent(): string;
+
+    /**
+     * Wrap up the writer after all items have been written
```
Comment (stefandoorn) [inline src/Writer/WriterInterface.php]: Maybe more clear: `Clear the writer after all items have been written`?

File: src/Writer/ExcelWriter.php [hunk 2]
```diff
@@ -86,4 +86,12 @@ private function prepare(): void
             $this->writer->prepare();
         }
     }
+
+    /**
+     * Wrap up the writer after all items have been written
```
Comment (stefandoorn) [inline src/Writer/ExcelWriter.php]: Can use `@inheritdoc` here

File: src/Exporter/ResourceExporterInterface.php [hunk 3]
```diff
@@ -20,4 +20,9 @@ public function setExportFile(string $filename): void;
      * @return string
      */
     public function getExportedData(): string;
+
+    /**
+     * Wrap up the writer after all items have been written
+     */
+    public function finish(): void;
```
Comment (stefandoorn) [inline src/Exporter/ResourceExporterInterface.php]: The downside of adding extra methods to the interface is that any implementation needs to provide them. The less, the better sometimes. WDYT @lsmith77 @solutionDrive-Alt on this PR?

File: src/Writer/WriterInterface.php (hunk 1 above)
Comment (enesaktay) [reply src/Writer/WriterInterface.php]: The description has been copied from the portphp writer interface, but if you think clear fits more I can use clear :)

File: src/Exporter/ResourceExporterInterface.php (hunk 3 above)
Comment (lsmith77) [reply src/Exporter/ResourceExporterInterface.php]: well for some it may be an empty implementation .. but I see no way around this, at least given how portphp is currently setup.

Comment (solutionDrive-Alt) [reply src/Exporter/ResourceExporterInterface.php]: I'm a bit out of context here. Is the reason why we need this method somewhere documented? I heard about the problem, that zero-byte files are generated, but I'm not entirely sure what it has to do with this finish-method...

Comment (enesaktay) [reply src/Exporter/ResourceExporterInterface.php]: @solutionDrive-Alt the excel cli export didnt call the finish method of the phpexcel writer, this caused the file to be created with zero-bytes

Comment (stefandoorn) [reply src/Exporter/ResourceExporterInterface.php]: Maybe we should look into some refactoring where we share more between CLI and UI exports, in order to make them as least different as possible. Maybe I'm missing something, but I think it would be a good improvement.

File: spec/Writer/CsvWriterSpec.php [hunk 4]
```diff
@@ -36,4 +36,12 @@ function it_delegates_the_data_to_the_wrapped_writer(Writer $csvWriter)
         $csvWriter->writeItem($data)->shouldBeCalled();
         $this->write($data);
     }
+
+    function it_finishes_the_file_creation_when_we_get_the_contents(Writer $csvWriter)
+    {
+        $csvWriter->setCloseStreamOnFinish(true)->shouldBeCalled();
```
Comment (lsmith77) [inline spec/Writer/CsvWriterSpec.php]: it seems like phpspec needs this .. but I would hope that there is some way to not have to mock this method since its an implementation detail we are not interested in testing here.

File: src/Exporter/ResourceExporterInterface.php (hunk 3 above)
Comment (lsmith77) [reply src/Exporter/ResourceExporterInterface.php]: this relates a bit to https://github.com/FriendsOfSylius/SyliusImportExportPlugin/issues/119 .. right now we are too heavily bound to portphp
